### PR TITLE
Set compiler version for jsp servlet

### PR DESCRIPTION
**Pull request by SonicBeard**
Default is 1.5 and results in an error that 1.6 is required.

### CODE REVIEW

**Comment by tnguyen14** [comment]
@arnaudroques Can this be merged?

**Comment by arnaudroques** [comment]
I'm not sure : this merge will impose 1.9 Java version. Maybe we can go for 1.7 instead ?

**Comment by tnguyen14** [comment]
Why? Why not 1.9? Just try it, and if any problem occurs then, it can be revisited later?

**Comment by arnaudroques** [comment]
Well, some of our users are using older version than 1.9
So this merge will break the .war for them.
I agree that 1.5 is pretty old. It's a question of trade-off : 1.7 seems fair to us.

**Comment by tnguyen14** [comment]
Ok - can you create a separate PR to make that change and release then?

**Comment by tnguyen14** [comment]
@arnaudroques I created #88 to have the same change as this PR, but use 1.7 instead. Please help me take a look.

**Pull request closed without merging**
