### PR TITLE
added docker build

### LINKED ISSUE #184: Missing GitHub releases and Docker images for v1.2021.8 & v1.2021.9
The GitHub releases haven't been created for the tags `v1.2021.8` & `v1.2021.9` and the Docker images haven't been created, but there are [release notes](https://plantuml.com/changes) for these.

### PR DESCRIPTION
**Pull request by mimam419**
# Description

Fixes the issue about docker images not generating on new releases.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvements (non-breaking runtime improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing Instructions

Recreating any of the existing tags should trigger a Github Action workflow that would generate new artefacts and push the necessary Docker images.

See [here](https://hub.docker.com/repository/docker/codeprefect/plantuml-server/tags?page=1&ordering=last_updated) for artefacts from the workflow on my fork.

@arnaudroques, it is important to configure the necessary docker configurations as secrets.

```
DOCKERHUB_USERNAME: plantuml-server
DOCKERHUB_TOKEN: obtain from DockerHub
```

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

[Fixes #184]

### CODE REVIEW

**Comment by arnaudroques** [comment]
@mimam419 Sorry for the delay, just created DOCKERHUB_USERNAME and DOCKERHUB_TOKEN as secret in github.
Tell me if there are still some stuff to do.
Thanks again!

**Comment by stevehipwell** [comment]
@arnaudroques is your username (`DOCKERHUB_USERNAME`) `plantuml`?

**Comment by arnaudroques** [comment]
> @arnaudroques is your username (`DOCKERHUB_USERNAME`) `plantuml`?

Yes, it is now. Initial value was wrongly setted.

**Comment by stevehipwell** [comment]
Have you tested a `docker login` locally with the token?

**Comment by arnaudroques** [comment]
@mimam419 Many thanks for your work. I have recreated tag v1.2021.10 and something has been pushed to Docker Hub.

**Comment by stevehipwell** [comment]
@arnaudroques I can confirm that you have a published Docker image and I'm just about to test it.

**Pull request merged**
