### PR TITLE
Added support for specifying format to proxy

### PR DESCRIPTION
**Pull request by halindrome**
The proxy servlet only could generate PNG. Should be possible to
proxy the other supported formats too.

### CODE REVIEW

**Comment by maximesinclair** [comment]
Thanks for your contribution. I just changed the parameter name (from *format* to *fmt*) to stay coherent with the other parameters (*idx* for *index*, *src* for *source*).

**Comment by halindrome** [comment]
reasonable - thanks!  Are you in charge of deploying this at plantuml.com?
And if so, do you know when it might get put there?

On Thu, Dec 10, 2015 at 10:31 AM, Maxime Sinclair <notifications@github.com>
wrote:

> Thanks for your contribution. I just changed the parameter name (from
> *format* to *fmt*) to stay coherent with the other parameters (*idx* for
> *index*, *src* for *source*).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plantuml/plantuml-server/pull/18#issuecomment-163679208>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by arnaudroques** [comment]
plantuml.com has just been updated. Very few test done, so we hope that this feature is working :-)

**Comment by halindrome** [comment]
Looks pretty good from here!  Here's an example from a spec we are working
on:
http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://raw.githubusercontent.com/w3c/webpayments/gh-pages/PaymentFlows/Card/MerchantHosted-CardPayment-CGProposal.pml

On Thu, Dec 10, 2015 at 12:45 PM, arnaudroques <notifications@github.com>
wrote:

> plantuml.com has just been updated. Very few test done, so we hope that
> this feature is working :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plantuml/plantuml-server/pull/18#issuecomment-163714264>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Pull request merged**
